# Generated by Django 6.0.5 on 2026-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_otp_customuser_otp_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
