# Generated by Django 6.0.5 on 2026-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
