# Generated by Django 6.0.5 on 2026-05-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
