# Generated by Django 6.0.5 on 2026-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_read_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
