# Generated by Django 6.0.5 on 2026-05-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='is_bulltet',
            field=models.BooleanField(default=False),
        ),
    ]
