# Generated by Django 6.0.5 on 2026-05-13 09:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_paragraph_is_bulltet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='is_bulltet',
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
