# Generated by Django 6.0.5 on 2026-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_paragraph_is_bulltet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='is_bulltet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.TextField(),
        ),
    ]
