# Generated by Django 6.0.5 on 2026-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_pending_email'),
        ('article', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(null=True, to='accounts.profile'),
        ),
    ]
