# Generated by Django 6.0.5 on 2026-05-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
