# Generated by Django 6.0.5 on 2026-05-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='is_bulltet',
        ),
    ]
