# Generated by Django 6.0.5 on 2026-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_remove_paragraph_is_bulltet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
