# Generated by Django 6.0.5 on 2026-05-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_pending_email'),
        ('article', '0013_alter_paragraph_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_articles', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='accounts.profile'),
        ),
    ]
